language: go
branches:
  only:
  - master
before_install: python --version
install:
  - go get -v github.com/spf13/hugo
  - sudo pip install s3cmd
  - sudo pip install awscli
  - nvm install node
script:
  - cd themes/westminsterhist && npm install --verbose && cd ../..
  - cd themes/westminsterhist && npm run build && cd ../..
  - hugo --enableGitInfo
  - s3cmd sync --acl-public --delete-removed --guess-mime-type public/ s3://ulsterworldly.com/
  - s3cmd put --acl-public --mime-type="text/css" -f public/css/*.css s3://ulsterworldly.com/css/
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
    email:
        on_failure: change
        on_success: change
