language: go
branches:
  only:
  - master
before_install: python --version
install:
  - go get -v github.com/spf13/hugo
  - sudo pip install s3cmd
  - nvm install node
script:
  - cd themes/westminsterhist && npm install && cd ../..
  - cd themes/westminsterhist && npm run build && cd ../..
  - hugo --enableGitInfo
  - s3cmd sync --delete-removed --acl-public --guess-mime-type --recursive public/ s3://ulsterworldly.com/
notifications:
    email:
        on_failure: always
