backend:
  name: git-gateway
  branch: master
display_url: 'https://ulsterworldly.com'
media_folder: static/images/
public_folder: /images/
collections:
  - name: blog posts
    label: Blog Posts
    description: |
      Posts (blog entries), visible in indexes and RSS feeds.
    folder: content/post
    create: true
    slug: '{{slug}}'
    display_fields: ['title', 'date', 'draft', 'people', 'tags']
    view_groups: 
      - label: Year
        field: date
        pattern: \d{4}
      - label: Tag
        field: tags
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: People
        name: people
        widget: list
        required: false
      - label: Description
        name: description
        widget: string
        required: false
      - label: Images Paths
        name: images
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Short
        name: short
        widget: boolean
        default: false
