backend:
  name: git-gateway
  branch: master
display_url: https://ulsterworldly.com
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "posts" 
    label: "Posts"    description: >
      Posts (blog entries), visible in indexes and RSS feeds.
    folder: "posts" # The path to the folder where the documents are stored
    create: true 
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
